server:
  port: 8030

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service # eureka server에 등록된 spring.application.name
          uri: lb://USER-SERVICE # user-service를 load balancing
          predicates:
            - Path=/user/**  # 해당 패턴에 대해서
          filters:
            - RewritePath=/user/?(?<segment>.*), /$\{segment} # URL을 변경
            - CustomAuthFilter # 해당 필터 클래스로 필터 실행

        - id: statdata-service
          uri: lb://STATDATA-SERVICE
          predicates:
            - Path=/statdata/**
          filters:
            - RewritePath=/statdata/?(?<segment>.*), /$\{segment}
            - CustomAuthFilter

        - id: mapdata-service
          uri: lb://MAPDATA-SERVICE
          predicates:
            - Path=/mapdata/**
          filters:
            - RewritePath=/mapdata/?(?<segment>.*), /$\{segment}
            - CustomAuthFilter

eureka:
  client:
    fetch-registry: true # 유레카 서비스에 자신을 주기적으로 등록
    register-with-eureka: true # 유레카 서비스가 시작할 때 레지스트리 정보를 로컬에 저장
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:8787/eureka} # Eureka 서버 주소

