server:
  port: 8000

spring:
  application:
    name: user-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:8787/eureka}



