server:
  port: 8787

spring:
  application:
    name: discover-service # eureka에서 사용하는 이름

eureka:
  client:
    fetch-registry: false # 유레카 서비스에 자신을 주기적으로 등록하지 않음 (즉, 클라이어언트로 사용 안함)
    register-with-eureka: false # 유레카 서비스가 시작할 때 레지스트리 정보를 로컬에 저장하지 않음 (즉, 클라이어언트로 사용 안함)
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:8787/eureka} # Eureka 서버 주소 (자기 자신을 주기 적으로 호출하기 때문에 서버도 필요함)
  server:
    enable-self-preservation: false # 유레카와 통신이 되지 않아도 서비스 등록을 삭제하지 않음